runtime: python39
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  PROJECT_ID: "spring-asset-476800-u6"
  REGION: "us-central1"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65

# VPC connector for Cloud SQL and Redis access
vpc_access_connector:
  name: "projects/spring-asset-476800-u6/locations/us-central1/connectors/youandinotai-connector"

# Service account with appropriate permissions
service_account: spring-asset-476800-u6@appspot.gserviceaccount.com

# Health checks
liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300
