# AWS SAM Template for 1-Click Launcher
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Team Claude For The Kids - Fund Generator Launcher

Parameters:
  UserEmail:
    Type: String
    Default: joshlcoleman@gmail.com
    Description: Email for notifications

Resources:
  # Lambda Function
  LauncherFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TeamClaudeFundLauncher
      Handler: aws-lambda-launcher.handler
      Runtime: nodejs20.x
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          CHARITY_NAME: Shriners Children's Hospitals
          DONATION_PERCENTAGE: 50
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /launch
            Method: get
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Description: Health check every 5 minutes

  # S3 Bucket for icon hosting
  IconBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'team-claude-launcher-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html

  # Bucket Policy for public read
  IconBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref IconBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${IconBucket.Arn}/*'

  # SNS Topic for alerts
  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: TeamClaudeFundAlerts
      Subscription:
        - Endpoint: !Ref UserEmail
          Protocol: email

  # CloudWatch Alarm
  ErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: TeamClaudeFundGeneratorErrors
      AlarmDescription: Alert on launcher errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlertTopic
      Dimensions:
        - Name: FunctionName
          Value: !Ref LauncherFunction

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/launch'
  
  IconBucketUrl:
    Description: S3 bucket URL for icon hosting
    Value: !GetAtt IconBucket.WebsiteURL
  
  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt LauncherFunction.Arn
