name: Feature Request
description: Suggest a new feature for Ai-Solutions.Store platforms
title: "[FEATURE]: "
labels: ["enhancement", "feature-request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We value your input.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or use case
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: Describe your proposed solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions have you considered?
      placeholder: Describe alternative approaches

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform would this feature benefit?
      multiple: true
      options:
        - youandinotai.com (Dating Platform)
        - ai-solutions.store (SaaS Marketplace)
        - youandinotai.online (Admin Dashboard)
        - Backend API
        - All platforms
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking work)
        - High (significant impact)
        - Medium (would be helpful)
        - Low (nice to have)
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how you would use this feature
      placeholder: Walk us through a typical scenario

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: Add any mockups, wireframes, or examples

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched for similar feature requests
          required: true
        - label: This feature aligns with the charitable mission
          required: false
        - label: I'm willing to help implement this feature
          required: false
