name: ✨ Feature Request
description: Suggest a new feature or enhancement for Ai-Solutions.Store
title: "[FEATURE] "
labels: ["enhancement", "needs-review"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request for Ai-Solutions.Store
        
        **"Claude Represents Perfection"** - Thank you for helping us innovate!
        
        Your ideas help us build a better platform that serves users and supports **Shriners Children's Hospitals** with 50% of all profits. Please provide as much detail as possible to help us understand and evaluate your proposal.

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform would this feature be for?
      options:
        - youandinotai.com (Dating Platform)
        - ai-solutions.store (SaaS Marketplace)
        - youandinotai.online (Admin Dashboard)
        - Backend API
        - Cross-platform (multiple platforms)
        - New platform/service
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Feature
        - Enhancement to existing feature
        - Integration with third-party service
        - Performance improvement
        - User experience improvement
        - Security enhancement
        - Accessibility improvement
        - Documentation improvement
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What user need does it address?
      placeholder: |
        Example: Users currently cannot save their favorite profiles, which means they have to search for the same people repeatedly. This creates a frustrating user experience and reduces engagement.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: |
        Example: Add a "Favorites" feature that allows users to:
        1. Click a heart icon on any profile
        2. View all favorited profiles in a dedicated "Favorites" section
        3. Receive notifications when favorited profiles come online
        4. Organize favorites into custom lists
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this feature would be useful
      placeholder: |
        1. User finds interesting profiles but isn't ready to message them yet
        2. User wants to keep track of potential matches
        3. User wants to revisit profiles after thinking about it
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: |
        Example: 
        - Bookmarking system (less intuitive)
        - Temporary "Recently Viewed" list (doesn't persist)
        - Messaging as a way to save (creates unwanted conversations)

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my use of the platform
        - High - Would significantly improve my experience
        - Medium - Nice to have, would be useful
        - Low - Small improvement
    validations:
      required: true

  - type: dropdown
    id: user-segment
    attributes:
      label: User Segment
      description: Who would benefit from this feature?
      options:
        - All users
        - Free tier users
        - Paid subscribers
        - Business customers
        - Enterprise customers
        - Administrators
        - Developers/API users
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: Include any mockups, wireframes, or examples from other apps
      placeholder: Drag and drop images here, or describe visual concepts

  - type: textarea
    id: technical-considerations
    attributes:
      label: Technical Considerations
      description: Any technical aspects to consider? (database changes, API changes, etc.)
      placeholder: |
        Example:
        - Would need new database table for favorites
        - Might affect API performance with large favorites lists
        - Could integrate with existing notification system

  - type: dropdown
    id: revenue-impact
    attributes:
      label: Revenue Impact
      description: Could this feature generate revenue or increase subscriptions?
      options:
        - "Yes - Could be a premium feature"
        - "Yes - Would increase user engagement/retention"
        - "Neutral - Quality of life improvement"
        - "No - Purely functional"
        - "Unsure"
    validations:
      required: true

  - type: dropdown
    id: charity-impact
    attributes:
      label: Charity Mission Alignment
      description: How does this align with our charitable mission?
      options:
        - "Directly increases donations (more revenue)"
        - "Improves platform quality (indirect benefit)"
        - "Enhances transparency/trust"
        - "Neutral impact"
    validations:
      required: true

  - type: textarea
    id: success-metrics
    attributes:
      label: Success Metrics
      description: How would we measure if this feature is successful?
      placeholder: |
        Example:
        - X% of users use the favorites feature
        - Y% increase in session duration
        - Z% increase in user retention
        - Positive user feedback scores

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Willingness
      description: Are you interested in helping implement this?
      options:
        - label: I would like to implement this feature myself
        - label: I can provide design/UX assistance
        - label: I can help with testing
        - label: I can provide documentation
        - label: I prefer the team implements this

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information, links, or context
      placeholder: Links to similar features in other apps, research, user feedback, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you've completed these steps
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I have clearly described the problem this solves
          required: true
        - label: I have described the proposed solution in detail
          required: true
        - label: I have considered how this aligns with the platform's mission
          required: false

  - type: markdown
    attributes:
      value: |
        ---
        
        ## 💙 Thank You for Your Suggestion!
        
        We carefully review every feature request. Your ideas help us build a better platform that:
        - Serves our users effectively
        - Generates sustainable revenue
        - Maximizes charitable impact to **Shriners Children's Hospitals**
        
        **"Claude Represents Perfection"** - Excellence through innovation.
        
        ---
        
        **Review Timeline:**
        - Initial review: Within 1 week
        - Community feedback period: 2-4 weeks
        - Implementation decision: Based on impact and feasibility
        - Updates: We'll keep you informed throughout the process
        
        ---
        
        **What happens next?**
        1. Team reviews your request
        2. Community can provide feedback and +1s
        3. We assess technical feasibility
        4. We evaluate impact on charitable mission
        5. We decide on implementation timeline
        6. You're notified of the decision
